"""The Claude Code plugin and the Codex/Claude configs agree with the code (docs/INTEGRATIONS.md).

Every spelling of the ``pcp mcp`` entry is generated by :mod:`pcp.mcp.config`, except
the plugin's static ``.mcp.json``, which is held to the generator here.  The skills and
the AGENTS.md block may only name subcommands, tools and packaged skills that exist, so
a rename breaks a test rather than a lab member's session.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import tomllib
from pathlib import Path

import pytest

from pcp.cli import cmd_integrate as integ
from pcp.cli.main import build_parser, main
from pcp.errors import UsageError
from pcp.mcp import config
from pcp.mcp.names import MCP_SERVER_NAME, TOOLS
from pcp.util.assets import skill_names, skill_text

ROOT = Path(__file__).resolve().parents[1]
PLUGIN = ROOT / "integrations" / "claude-code"
MARKETPLACE = ROOT / ".claude-plugin" / "marketplace.json"
PLUGIN_TEXTS = sorted([*PLUGIN.glob("skills/*/SKILL.md"), *PLUGIN.glob("commands/*.md")])


def _subcommands() -> set[str]:
    sub = next(a for a in build_parser()._actions if a.dest == "command")
    return set(sub.choices)


# ------------------------------------------------------------------ generated configs
def test_codex_toml_parses_to_the_server_entry():
    doc = tomllib.loads(config.codex_toml(pcp="/opt/pcp bin/pcp"))
    assert list(doc["mcp_servers"]) == [MCP_SERVER_NAME]
    entry = doc["mcp_servers"][MCP_SERVER_NAME]
    assert {"command": entry["command"], "args": entry["args"]} == config.server_entry(pcp="/opt/pcp bin/pcp")
    assert entry["tool_timeout_sec"] > 60 and entry["startup_timeout_sec"] > 10  # Codex defaults are too short


def test_claude_json_and_add_line_spell_the_same_entry():
    doc = json.loads(json.dumps(config.claude_mcp_json(pcp="pcp", workspace="/w")))
    assert doc == {"mcpServers": {MCP_SERVER_NAME: {"command": "pcp", "args": ["mcp", "--workspace", "/w"]}}}
    argv = config.claude_add_argv(pcp="pcp", workspace="/w", scope="project")
    assert argv[argv.index("--") - 1] == MCP_SERVER_NAME and argv[argv.index("--") + 1:] == ["pcp", "mcp", "--workspace", "/w"]
    assert config.codex_add_argv()[3] == MCP_SERVER_NAME
    assert config.server_entry() == {"command": "pcp", "args": ["mcp"]}


def test_worker_mcp_json_is_unchanged(tmp_path):
    path = config.write_mcp_config(tmp_path)
    assert json.loads(path.read_text()) == {
        "mcpServers": {MCP_SERVER_NAME: {"command": "pcp", "args": ["mcp", "--workspace", str(tmp_path)]}}
    }


# ------------------------------------------------------------------------- the plugin
def test_plugin_mcp_json_is_the_generated_entry():
    bundled = json.loads((PLUGIN / ".mcp.json").read_text())
    assert bundled == config.claude_mcp_json(pcp="pcp", workspace="${CLAUDE_PROJECT_DIR}")


def test_plugin_manifest_matches_marketplace_and_package():
    plugin = json.loads((PLUGIN / ".claude-plugin" / "plugin.json").read_text())
    market = json.loads(MARKETPLACE.read_text())
    (entry,) = [p for p in market["plugins"] if p["name"] == plugin["name"]]
    assert (ROOT / entry["source"]).resolve() == PLUGIN.resolve()
    version = tomllib.loads((ROOT / "pyproject.toml").read_text())["project"]["version"]
    assert plugin["version"] == version, "bump integrations/claude-code/.claude-plugin/plugin.json with pyproject"


@pytest.mark.parametrize("path", PLUGIN_TEXTS, ids=lambda p: p.parent.name if p.name == "SKILL.md" else p.stem)
def test_plugin_text_names_only_real_things(path):
    text = path.read_text()
    front = re.match(r"---\n(.*?)\n---\n", text, re.S)
    assert front and re.search(r"^description: \S", front.group(1), re.M), "frontmatter needs a description"
    if path.name == "SKILL.md":
        assert re.search(rf"^name: {re.escape(path.parent.name)}$", front.group(1), re.M)
    _assert_names_real(text)


def test_agents_md_block_names_only_real_things():
    block = integ.agents_md_block()
    assert all(f"`{t}`" in block for t in TOOLS)
    _assert_names_real(block)


def test_integrations_doc_names_only_real_things():
    _assert_names_real((ROOT / "docs" / "INTEGRATIONS.md").read_text())


def _assert_names_real(text: str) -> None:
    subs = _subcommands()
    # Commands are quoted: inline `pcp x ...` or a code-block line starting `pcp x`.
    for cmd in re.findall(r"(?:`|^)pcp ([a-z][a-z-]*)", text, re.M):
        assert cmd in subs, f"`pcp {cmd}` is not a subcommand"
    for name in re.findall(r"pcp skill show (\w+)", text):
        assert f"{name}.md" in skill_names()
    for tool in set(re.findall(r"\b(proof_[a-z]+|premise_search|notation_resolve|verify_node)\b", text)):
        assert tool in TOOLS, f"{tool} is not an MCP tool"


@pytest.mark.skipif(shutil.which("claude") is None, reason="claude CLI not installed")
def test_claude_validates_plugin_and_marketplace():
    for target in (PLUGIN, ROOT):
        out = subprocess.run(["claude", "plugin", "validate", str(target)], capture_output=True, text=True, timeout=60, check=False)
        assert out.returncode == 0, out.stdout + out.stderr


# ----------------------------------------------------------------------------- merges
def test_codex_merge_appends_is_idempotent_and_refuses_to_clobber():
    table = config.codex_toml(pcp="pcp")
    base = '# mine\nmodel = "o"\n\n[mcp_servers.other]\ncommand = "x"\n'
    out, changed = integ.merge_codex_toml(base, table)
    assert changed and out.startswith(base)
    assert set(tomllib.loads(out)["mcp_servers"]) == {"other", MCP_SERVER_NAME}
    assert integ.merge_codex_toml(out, table) == (out, False)
    with pytest.raises(UsageError, match="--force"):
        integ.merge_codex_toml(out, config.codex_toml(pcp="/abs/pcp"))


def test_codex_force_replaces_the_table_and_its_subtables():
    old = '[mcp_servers.pcp]\ncommand = "old"\n\n[mcp_servers.pcp.env]\nA = "1"\n\n[profiles.x]\nmodel = "m"\n'
    out, changed = integ.merge_codex_toml(old, config.codex_toml(pcp="new"), force=True)
    doc = tomllib.loads(out)
    assert changed and doc["mcp_servers"][MCP_SERVER_NAME]["command"] == "new"
    assert "env" not in doc["mcp_servers"][MCP_SERVER_NAME] and doc["profiles"] == {"x": {"model": "m"}}


def test_codex_force_on_a_dotted_key_table_is_a_usageerror_not_a_crash():
    """A dotted key under ``[mcp_servers]`` isn't a header ``_drop_table`` can remove, so
    the appended ``[mcp_servers.pcp]`` header collides with it; tomllib refuses to parse
    the result and that must surface as the usual UsageError, not TOMLDecodeError."""
    old = '[mcp_servers]\npcp.command = "old"\n'
    with pytest.raises(UsageError, match="could not rewrite"):
        integ.merge_codex_toml(old, config.codex_toml(pcp="new"), force=True)


def test_codex_force_on_an_inline_table_is_a_usageerror_not_a_crash():
    old = '[mcp_servers]\npcp = { command = "old" }\n'
    with pytest.raises(UsageError, match="could not rewrite"):
        integ.merge_codex_toml(old, config.codex_toml(pcp="new"), force=True)


def test_drop_table_keeps_a_comment_that_precedes_the_next_header():
    old = (
        '[mcp_servers.pcp]\ncommand = "old"\n\n'
        "# NOTE: kept for a reason\n"
        '[mcp_servers.other]\ncommand = "x"\n'
    )
    out, changed = integ.merge_codex_toml(old, config.codex_toml(pcp="new"), force=True)
    assert changed
    assert "# NOTE: kept for a reason" in out
    assert out.index("# NOTE: kept for a reason") < out.index("[mcp_servers.other]")
    assert tomllib.loads(out)["mcp_servers"]["other"]["command"] == "x"


def test_header_regex_does_not_treat_a_nested_array_continuation_line_as_a_header():
    """``args = [\\n  [1, 2],\\n]`` inside the dropped table must not be mistaken for the
    start of a new (kept) table -- the whole dropped table must go."""
    old = (
        "[mcp_servers.pcp]\n"
        'command = "old"\n'
        "matrix = [\n"
        "  [1, 2],\n"
        "]\n\n"
        '[mcp_servers.other]\ncommand = "x"\n'
    )
    out = integ._drop_table(old)
    assert "matrix" not in out and "old" not in out
    assert 'command = "x"' in out


def test_claude_merge_keeps_other_servers():
    existing = json.dumps({"mcpServers": {"other": {"command": "x"}}, "extra": 1})
    out, changed = integ.merge_claude_json(existing, config.claude_mcp_json())
    data = json.loads(out)
    assert changed and data["extra"] == 1 and set(data["mcpServers"]) == {"other", MCP_SERVER_NAME}
    assert integ.merge_claude_json(out, config.claude_mcp_json()) == (out, False)
    with pytest.raises(UsageError):
        integ.merge_claude_json(out, config.claude_mcp_json(pcp="/abs/pcp"))


@pytest.mark.parametrize("existing", ["[]", "null", '"a string"', "42"])
def test_claude_merge_refuses_a_non_object_file_instead_of_crashing(existing):
    with pytest.raises(UsageError, match=r"\.mcp\.json"):
        integ.merge_claude_json(existing, config.claude_mcp_json())


def test_claude_merge_refuses_a_non_object_mcpservers_instead_of_crashing():
    existing = json.dumps({"mcpServers": None})
    with pytest.raises(UsageError, match="mcpServers"):
        integ.merge_claude_json(existing, config.claude_mcp_json())


def test_agents_md_merge_replaces_the_block_in_place():
    block = integ.agents_md_block()
    once = integ.merge_agents_md("# Project\n\nrules\n", block)
    assert once.startswith("# Project\n\nrules\n\n<!-- pcp:begin")
    assert integ.merge_agents_md(once, block) == once
    stale = once.replace("proof-copilot (`pcp`)", "old heading") + "\ntrailer\n"
    assert integ.merge_agents_md(stale, block) == once + "\ntrailer\n"


# -------------------------------------------------------------------------------- CLI
def test_cli_writes_codex_and_project_configs(tmp_path, monkeypatch, capsys):
    monkeypatch.setenv("CODEX_HOME", str(tmp_path / "codex"))
    assert main(["integrate", "codex", "--write", "--pcp", "pcp"]) == 0
    assert tomllib.loads((tmp_path / "codex" / "config.toml").read_text())["mcp_servers"][MCP_SERVER_NAME]["command"] == "pcp"
    proj = tmp_path / "proj"
    proj.mkdir()
    assert main(["integrate", "claude", "--write", "--project", str(proj)]) == 0
    assert json.loads((proj / ".mcp.json").read_text()) == config.claude_mcp_json(pcp="pcp")
    assert main(["integrate", "codex", "--write", "--project", str(proj)]) == 0
    assert (proj / ".codex" / "config.toml").exists()
    assert main(["integrate", "agents-md", "--write", "--project", str(proj)]) == 0
    assert "pcp skill show prover" in (proj / "AGENTS.md").read_text()
    assert main(["integrate", "claude", "--write"]) == 2  # user scope is `claude mcp add`, never a file we own


def test_cli_write_preserves_a_symlinked_target_and_its_mode(tmp_path, monkeypatch):
    """A dotfiles-managed ``~/.codex/config.toml`` (symlink) and its 0640 mode must
    survive a `pcp integrate codex --write`."""
    codex_home = tmp_path / "codex"
    codex_home.mkdir()
    dotfiles = tmp_path / "dotfiles"
    dotfiles.mkdir()
    real = dotfiles / "config.toml"
    real.write_text('model = "o"\n', encoding="utf-8")
    real.chmod(0o640)
    link = codex_home / "config.toml"
    link.symlink_to(real)
    monkeypatch.setenv("CODEX_HOME", str(codex_home))

    assert main(["integrate", "codex", "--write", "--pcp", "pcp"]) == 0

    assert link.is_symlink() and link.resolve() == real
    assert tomllib.loads(real.read_text())["mcp_servers"][MCP_SERVER_NAME]["command"] == "pcp"
    assert os.stat(real).st_mode & 0o777 == 0o640


def test_cli_prints_parseable_codex_toml(capsys):
    assert main(["integrate", "codex", "--pcp", "pcp"]) == 0
    out = capsys.readouterr().out
    table = out.split("\n\n# or")[0]
    assert tomllib.loads(table)["mcp_servers"][MCP_SERVER_NAME] == tomllib.loads(config.codex_toml())["mcp_servers"][MCP_SERVER_NAME]


def test_skill_show_prints_the_packaged_norms(capsys):
    assert main(["skill", "show", "prover"]) == 0
    assert capsys.readouterr().out == skill_text("prover.md")
    assert main(["skill", "show", "nope"]) == 2
    assert main(["skill", "list"]) == 0
    assert "logatom" in capsys.readouterr().out
