"""``pcp integrate`` and ``pcp skill``: hand an operator's agent the tools and the norms.

``pcp integrate claude|codex`` prints -- and with ``--write`` merges into the client's
config -- the ``pcp mcp`` server entry, always built by :mod:`pcp.mcp.config` so no
second spelling of it exists.  ``pcp integrate agents-md`` prints the block a Codex
user puts in ``AGENTS.md``.  ``pcp skill show NAME`` prints a packaged worker skill
(``pcp/assets/skills``, docs/ARCHITECTURE.md 8): the Claude Code plugin's skills and
the AGENTS.md block point at it instead of copying the text, so an interactive prover
reads exactly the norms the installed version's workers are given.
See docs/INTEGRATIONS.md.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shlex
import shutil
import sys
import tomllib
from pathlib import Path
from typing import Any

from pcp.cli.common import absolute
from pcp.errors import UsageError
from pcp.mcp.config import (
    MCP_CONFIG_FILE,
    claude_add_argv,
    claude_mcp_json,
    codex_add_argv,
    codex_toml,
)
from pcp.mcp.names import BLURBS, MCP_SERVER_NAME, TOOLS
from pcp.util.assets import skill_names, skill_text
from pcp.util.io import atomic_write_text, json_dumps

TARGETS = ("claude", "codex", "agents-md")
AGENTS_FILE = "AGENTS.md"
BEGIN = "<!-- pcp:begin (generated by `pcp integrate agents-md`; edits inside are replaced) -->"
END = "<!-- pcp:end -->"
_BLOCK = re.compile(r"<!-- pcp:begin[^\n]*-->.*?<!-- pcp:end -->\n?", re.S)
_TABLE = re.compile(r"^\s*\[\s*mcp_servers\.(\"?)" + re.escape(MCP_SERVER_NAME) + r"\1\s*(\]|\.)")
# A real table header, on a line by itself (a continuation line of a nested array,
# e.g. "  [1, 2]," inside a multi-line value, also starts with "[" but is not one).
_HEADER = re.compile(r'^\s*\[\[?[A-Za-z0-9_."-]+\]\]?\s*(#.*)?$')


# --------------------------------------------------------------------------- skill
def skill_file(name: str) -> str:
    """``prover`` or ``prover.md`` -> ``prover.md``; a clear error naming the choices."""
    fname = name if name.endswith(".md") else f"{name}.md"
    if fname not in skill_names():
        choices = ", ".join(n.removesuffix(".md") for n in skill_names())
        raise UsageError(f"no packaged skill {name!r}; choose from: {choices}")
    return fname


def cmd_skill(args: argparse.Namespace) -> int:
    if args.action == "show" and args.name is None:
        raise UsageError("pcp skill show NAME; `pcp skill list` names them")
    if args.action == "list":
        for fname in skill_names():
            heading = next((ln.lstrip("# ").strip() for ln in skill_text(fname).splitlines() if ln.strip()), "")
            print(f"{fname.removesuffix('.md'):<12} {heading}")
        return 0
    sys.stdout.write(skill_text(skill_file(args.name)))
    return 0


# ----------------------------------------------------------------------- agents-md
def agents_md_block() -> str:
    """The AGENTS.md block: the tools (from :data:`BLURBS`) and pointers to the norms."""
    tools = "\n".join(f"- `{t}` -- {BLURBS[t]}" for t in TOOLS)
    return f"""{BEGIN}
## proof-copilot (`pcp`)

This project uses proof-copilot for Rocq/Iris proofs. The `{MCP_SERVER_NAME}` MCP server
(`pcp mcp`) gives you the Iris proof state per hypothesis, without editing or recompiling:

{tools}

Workflow: `proof_open` the lemma, `proof_step`/`proof_try` tactics, and ask
`proof_ledger` (blame / where_did_it_go / leftovers) whenever a spatial hypothesis goes
missing or `iFrame` fails; get `iDestruct` patterns from `proof_destruct`, lemma names from
`premise_search`; check the finished body with `verify_node`. File paths are relative
to the project root.

Before proving an Iris lemma, read the norms and follow them:
- `pcp skill show prover` -- always (statement discipline, IPM technique, when to stop);
- `pcp skill show logatom` -- for logically atomic triples (`<<< ... >>>`, `atomic_update`);
- `pcp skill show invariants` -- when choosing or strengthening an invariant.

Orchestrated runs (the operator's daily loop): `pcp prove FILE LEMMA --plan plan.v`
(`--supervise` to detach), `pcp status`, `pcp handoff NODE`, `pcp serve`. A run resumes
from `.pcp/graph.db` when re-run. If a tool reports the toolchain missing, run `pcp doctor`.
{END}
"""


def merge_agents_md(existing: str, block: str) -> str:
    """Replace the generated block in place, or append it; idempotent."""
    if _BLOCK.search(existing):
        return _BLOCK.sub(lambda _m: block, existing, count=1)
    sep = "" if not existing else ("\n" if existing.endswith("\n") else "\n\n")
    return f"{existing}{sep}{block}"


# ---------------------------------------------------------------------------- codex
def merge_codex_toml(existing: str, table: str, *, force: bool = False) -> tuple[str, bool]:
    """``(new text, changed)``: add the ``[mcp_servers.pcp]`` table, or replace it with ``force``.

    Edited as text so the user's comments and layout survive; the result is re-parsed
    and must contain exactly the wanted entry.
    """
    want = tomllib.loads(table)["mcp_servers"][MCP_SERVER_NAME]
    try:
        have = tomllib.loads(existing).get("mcp_servers", {}).get(MCP_SERVER_NAME)
    except tomllib.TOMLDecodeError as exc:
        raise UsageError(f"the existing Codex config is not valid TOML ({exc}); fix it first") from exc
    if have == want:
        return existing, False
    if have is not None:
        if not force:
            raise UsageError(
                f"[mcp_servers.{MCP_SERVER_NAME}] already exists with different settings; "
                "pass --force to replace it (or edit it by hand)"
            )
        existing = _drop_table(existing)
    sep = "" if not existing or existing.endswith("\n\n") else ("\n" if existing.endswith("\n") else "\n\n")
    out = f"{existing}{sep}{table}"
    try:
        rewritten = tomllib.loads(out).get("mcp_servers", {}).get(MCP_SERVER_NAME)
    except tomllib.TOMLDecodeError:
        rewritten = None  # a dotted-key or inline-table form left a table conflict; fall through
    if rewritten != want:
        raise UsageError(
            f"could not rewrite [mcp_servers.{MCP_SERVER_NAME}] in place (inline or dotted-key form?); "
            "edit the Codex config by hand"
        )
    return out, True


def _drop_table(text: str) -> str:
    """Remove ``[mcp_servers.pcp]`` and its sub-tables (``[mcp_servers.pcp.env]``).

    A blank line or comment sitting between the dropped table and whatever comes next
    reads as a preamble to that next thing, not as part of the table being dropped
    (a ``# NOTE`` right above ``[mcp_servers.other]`` must survive) -- so it is held
    back and only actually dropped if the table turns out to continue past it.
    """
    out: list[str] = []
    pending: list[str] = []
    skipping = False
    for line in text.splitlines(keepends=True):
        if _HEADER.match(line):
            was_skipping = skipping
            skipping = bool(_TABLE.match(line))
            if was_skipping and not skipping:
                out.extend(pending)
            pending = []
            if skipping:
                continue
            out.append(line)
            continue
        if skipping:
            stripped = line.strip()
            if stripped == "" or stripped.startswith("#"):
                pending.append(line)
            else:
                pending = []
        else:
            out.append(line)
    return "".join(out)


def codex_home() -> Path:
    return Path(os.environ.get("CODEX_HOME") or Path.home() / ".codex")


# ---------------------------------------------------------------------------- claude
def merge_claude_json(existing: str, doc: dict[str, Any], *, force: bool = False) -> tuple[str, bool]:
    """``(new text, changed)``: set ``mcpServers.pcp`` in a ``.mcp.json``, keeping the rest."""
    try:
        data = json.loads(existing) if existing.strip() else {}
    except json.JSONDecodeError as exc:
        raise UsageError(f"the existing {MCP_CONFIG_FILE} is not valid JSON ({exc}); fix it first") from exc
    if not isinstance(data, dict):
        raise UsageError(f"the existing {MCP_CONFIG_FILE} is not a JSON object; fix it first")
    servers = data.setdefault("mcpServers", {})
    if not isinstance(servers, dict):
        raise UsageError(f'the existing {MCP_CONFIG_FILE} has a non-object "mcpServers"; fix it first')
    want = doc["mcpServers"][MCP_SERVER_NAME]
    have = servers.get(MCP_SERVER_NAME)
    if have == want:
        return existing, False
    if have is not None and not force:
        raise UsageError(
            f"{MCP_CONFIG_FILE} already has a different {MCP_SERVER_NAME!r} server; pass --force to replace it"
        )
    servers[MCP_SERVER_NAME] = want
    return json_dumps(data) + "\n", True


# --------------------------------------------------------------------------- command
def installed_pcp() -> str:
    """The absolute path of this ``pcp``, for configs a harness reads without our PATH."""
    argv0 = Path(sys.argv[0])
    if argv0.name == "pcp" and argv0.is_file():
        return str(argv0.absolute())  # not resolve(): keep the stable ~/.local/bin symlink
    return shutil.which("pcp") or "pcp"


def _write(path: Path, text: str, changed: bool) -> None:
    if changed:
        # A user-facing config: don't replace ~/.codex/config.toml (often a dotfiles
        # symlink) with a plain file, and don't force mkstemp's 0600 onto it.
        atomic_write_text(path, text, follow_symlinks=True, keep_mode=True)
        print(f"wrote {path}", file=sys.stderr)
    else:
        print(f"{path}: already up to date", file=sys.stderr)


def cmd_integrate(args: argparse.Namespace) -> int:
    project = absolute(args.project) if args.project else None
    if project is not None and not project.is_dir():
        raise UsageError(f"{project}: not a directory")

    if args.target == "agents-md":
        block = agents_md_block()
        if not args.write:
            sys.stdout.write(block)
            return 0
        target = (project or Path.cwd().resolve()) / AGENTS_FILE
        existing = target.read_text(encoding="utf-8") if target.exists() else ""
        merged = merge_agents_md(existing, block)
        _write(target, merged, merged != existing)
        return 0

    # A project file is shared (committed) and must not carry this machine's path; a
    # user-level entry is read by a harness that may not have our PATH.
    pcp = args.pcp or ("pcp" if project is not None else installed_pcp())
    # No --workspace: both clients start the server in the project directory, so one
    # entry serves every project (docs/INTEGRATIONS.md, "Which workspace").
    if args.target == "claude":
        doc = claude_mcp_json(pcp=pcp)
        if args.write:
            if project is None:
                raise UsageError(
                    "--write for claude needs --project DIR (it writes DIR/.mcp.json); for a user-level "
                    "server run the printed `claude mcp add` line instead"
                )
            target = project / MCP_CONFIG_FILE
            existing = target.read_text(encoding="utf-8") if target.exists() else ""
            text, changed = merge_claude_json(existing, doc, force=args.force)
            _write(target, text, changed)
            return 0
        scope = "project" if project is not None else "user"
        print(f"# {project / MCP_CONFIG_FILE if project else 'a project .mcp.json'}:")
        print(json_dumps(doc))
        print(f"\n# or register it with the Claude Code CLI ({scope} scope):")
        print(shlex.join(claude_add_argv(pcp=pcp, scope=scope)))
        return 0

    table = codex_toml(pcp=pcp)
    if not args.write:
        where = project / ".codex/config.toml" if project else codex_home() / "config.toml"
        print(f"# add to {where}:")
        sys.stdout.write(table)
        print("\n# or (without the longer timeouts pcp needs):")
        print(shlex.join(codex_add_argv(pcp=pcp)))
        return 0
    target = (project / ".codex" if project else codex_home()) / "config.toml"
    existing = target.read_text(encoding="utf-8") if target.exists() else ""
    text, changed = merge_codex_toml(existing, table, force=args.force)
    _write(target, text, changed)
    return 0

